name = "tester"
description = "Shiny new project"
version = "0.0.0"

authors = ["Henrik Harkonen"]
maintainers = ["Henrik Harkonen <heharkon@iki.fi>"]
maintainers-logins = ["heharkon"]

executables = ["tester"]

[[depends-on]]  # This line was added by `alr with`
sylcode = "~0.0.0"  # This line was added by `alr with`
